# Generated by Django 4.2 on 2025-01-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='키워드')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '키워드',
                'verbose_name_plural': '키워드 목록',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('url', models.URLField(verbose_name='기사 링크')),
                ('source', models.CharField(max_length=50, verbose_name='언론사')),
                ('published_at', models.DateTimeField(verbose_name='발행일')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='요약')),
                ('content', models.TextField(blank=True, null=True, verbose_name='본문')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('keywords', models.ManyToManyField(related_name='articles', to='news.keyword', verbose_name='키워드')),
            ],
            options={
                'verbose_name': '기사',
                'verbose_name_plural': '기사 목록',
                'ordering': ['-published_at'],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-published_at'], name='news_articl_publish_62720b_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['title'], name='news_articl_title_dca5f8_idx'),
        ),
    ]
