# Generated by Django 4.2 on 2025-01-21 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=100)),
                ('crawled_time', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('articles', models.JSONField()),
                ('analysis', models.JSONField()),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='newssummary',
            index=models.Index(fields=['keyword'], name='news_newssu_keyword_bd4884_idx'),
        ),
        migrations.AddIndex(
            model_name='newssummary',
            index=models.Index(fields=['created_at'], name='news_newssu_created_0485c3_idx'),
        ),
    ]
